name: WorkWechatNotice
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: bash wechat_notice.sh ${{ secrets.Work_Wechat_Bot_Key_01 }}
